{
 "title": "Accident Prediction Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DRIFT STATUS",
   "type": "stat",
   "description": "Indique si pas de drift ou drift détecté",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "accident_model_drift_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Débit de prédicitons",
   "type": "timeseries",
   "description": "Prédictions / seconde (moyenne glissante 1mn)",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "rate(accident_predictions_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DRIFT SCORE",
   "type": "gauge",
   "description": "Donne la valeur du score. Permet d'anticiper le risque de drift",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "accident_model_drift_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nombre total de prédictions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "targets": [
    { "expr": "accident_predictions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latence moyenne des prédictions",
   "type": "timeseries",
   "description": "Temps de réponse moyen par requête (fenêtre glissante 1mn)",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(accident_prediction_latency_seconds_sum[1m])/rate(accident_prediction_latency_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de requêtes mesurées",
   "type": "timeseries",
   "description": "Nombre total de requêtes capturées pour le calcul de la latence moyenne.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "accident_prediction_latency_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Version",
   "type": "timeseries",
   "description": "Version utilisée pour les KPIs",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 15 },
   "targets": [
    { "expr": "accident_model_version", "legendFormat": "__auto" }
   ]
  }
 ]
}