apiVersion: v1
kind: ConfigMap
metadata:
  name: accidents-severity-config
  namespace: accidents-severity
data:
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
  UV_LINK_MODE: "copy"
  GIT_PYTHON_REFRESH: "quiet"
  MLFLOW_HTTP_REQUEST_TIMEOUT: "60"
  DATABASE_URL: "postgresql://airflow:airflow@postgres-service:5432/airflow"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: accidents-severity
type: Opaque
data:
  POSTGRES_USER: YWlyZmxvdw==      # airflow
  POSTGRES_PASSWORD: YWlyZmxvdw==  # airflow
  POSTGRES_DB: YWlyZmxvdw==        # airflow