# ============================================================
# MLflow : Deployment + Service
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: accidents-severity
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      initContainers:
        - name: wait-for-postgres
          image: localhost:8081/busybox:1.36
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "until nc -z postgres-service 5432; do echo 'Attente Postgres...'; sleep 3; done"]
      containers:
        - name: mlflow
          image: localhost:8081/accidents_severity-mlflow:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_URL
            - name: MLFLOW_HTTP_REQUEST_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MLFLOW_HTTP_REQUEST_TIMEOUT
          volumeMounts:
            - name: artifacts
              mountPath: /app/artifacts
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 35
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 15
      volumes:
        - name: artifacts
          persistentVolumeClaim:
            claimName: mlflow-artifacts-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: accidents-severity
  labels:
    app: mlflow
spec:
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
