apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accidents-severity

resources:
  - 00-namespace.yaml
  - 01-configmap-secret.yaml
  - 02-pvcs.yaml
  - 03-postgres.yaml
  - 04-mlflow.yaml
  #- 05-train-job.yaml #uniquemeent à lancer à la main, car lancé par airflow
  - 06-api.yaml
  - 07-airflow.yaml
  - 08-prometheus.yaml
  - 09-grafana.yaml
  - 10-ingress.yaml
